version: '3'

services:

  nginx:
    build: 
      context: ./nginx
    image: kayphaz/nginx-custom
    container_name: nginx
    restart: always
    networks: 
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - node

  node:
    build:
      context: ./node
    image: kayphaz/node-custom
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s npx nodemon ./app/index.js
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge